### PR TITLE
Web based query interface

### PR DESCRIPTION
**Pull request by fabian-z**
For my own testing and development with Ekanite, I have created a small web based query interface.
In my pull request, it replaces the telnet query interface.
I am unsure if the former interface was also meant to be used as an API of sorts.
In this case, I may add an RESTful endpoint to my PR if there is interest. This may also be interesting for further expansion.

TLS protection and authentication is currently not handled by this code and should be done via e.g. nginx for production setups.

Looking forward to your feedback!

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @fabian-z -- I like the idea, and will run your code shortly to check out the functionality.

However, the simple telnet-like interface is not going away, as I want to build a more sophisticated CLI at some point, and it will use that interface. I would be interested in adding this to ekanite, but it must be implemented as a distinct server within the system, which would listen on a different port.

Make sense?

**Comment by fabian-z** [comment]
:+1: for a nice CLI application! :tada: 

Even though I definitely see your point, I would like to bring up some thoughts about security and future extensibility of the telnet interface here:

Telnet itself is more difficult to secure than a simple HTTP/REST endpoint. You would need e.g. SSH port forwarding to safely run the CLI on your own machine instead of a shell on the Ekanite server.
Using a simple nginx setup with Basic Auth over TLS would enable the CLI application to be usable on any client.

Also, I think expanding the telnet interface would result in the equivalent of creating a special wire protocol for Ekanite over time. I can imagine that issues such as versioning of the API (different server <-> client versions) and passing complex structures back and forth could get problematic at some point in time. If this kind of effort is planned, building on something akin to [protobuf](https://github.com/golang/protobuf) might be an option, too.

With that being said, I don't want to question any of your design decisions here - I am glad you like my contribution as I think it will be helpful in its own right also when co-existing with the telnet interface. I will be glad to contribute my code as a separate server entity with its own configuration option if you would like me to.

Keen on your feedback regarding functionality!

**Comment by otoolep** [comment]
Thanks @fabian-z 

>Telnet itself is more difficult to secure than a simple HTTP/REST endpoint. 

Agreed. If someone doesn't want to run the insecure system, we should update the code so that it can be disabled if no address is passed on the command line for the query server. There is no need to rip it out though, it can co-exist.

>Also, I think expanding the telnet interface would result in the equivalent of creating a special wire protocol for Ekanite over time.

Yes, this may make sense in the future, especially for paging of results.

**Comment by fabian-z** [comment]
I appreciate the dialogue.

Your point for an optional, modular interface system is clear. Do you think both interfaces should be opt-in or should one be preferred? I think having at least one standard interface (while documenting both) would be beneficial for first time users.

Also, I'd love to hear what you think about making the tests independent from any interface (cf65d95) and also about the syntax reference URL change in 176d4c0.

When that is clear, I think it will be easier for me to start a new branch/PR and to incorporate everything there.

**Comment by otoolep** [comment]
>Your point for an optional, modular interface system is clear. Do you think both interfaces should be opt-in or should one be preferred? I think having at least one standard interface (while documenting both) would be beneficial for first time users.

The telnet server is opt-out after my most recent change to master. All other interfaces could be opt-in. 

>Also, I'd love to hear what you think about making the tests independent from any interface (cf65d95) and also about the syntax reference URL change in 176d4c0.

Making the tests independent makes sense. I don't follow you about the syntax change.

>When those aspects are decided upon, I think it will be easier for me to start a new branch/PR and to incorporate everything there.

Sounds good, thanks @fabian-z

**Comment by otoolep** [comment]
@fabian-z -- do you still plan to integrate the web server alongside the telnet server? If not, I may use your code as inspiration, and do just that.

**Comment by fabian-z** [comment]
@otoolep: It's still on my TODO list and I think I will find time for the needed adaptions (in a new PR) during the next week. My current workload made it difficult for me to get around implementing it earlier.
With that being said, if you want to implement my suggestion before next week, feel free to reuse my work as much as you can. :smile:

**Comment by fabian-z** [comment]
Closing here in favor of v2 PR

**Pull request closed without merging**
